name: NuGet Deploy (Prerelease)

on:
  push:
    branches: [ master ]

env:
  VERSION_SUFFIX: beta-${{ github.run_number }}

jobs:
  publish-prerelease:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack Localizer.Net
        run: dotnet pack --no-restore -c Release src/Localizer.Net/Localizer.Net.csproj --version-suffix $VERSION_SUFFIX
      - name: Pack Localizer.Net.Json
        run: dotnet pack --no-restore -c Release src/Localizer.Net.Json/Localizer.Net.Json.csproj --version-suffix $VERSION_SUFFIX

      - name: Upload Localizer.Net
        run: dotnet nuget push src/Localizer.Net/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      - name: Upload Localizer.Net.Json
        run: dotnet nuget push src/Localizer.Net.Json/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
